image: python:3.7-alpine

pages:
  stage: deploy
  script:
  - apk update
  - apk add make automake gcc g++ subversion python3-dev
  - pip install -U sphinx sphinx-rtd-theme pandas IPython psutil
  - sphinx-build -b html docs/source public

  artifacts:
    paths:
    - public
  only:
  - master
