image: python:latest

stages:
  - test
  - build
  - deploy

before_script:
  - pip install poetry
  - poetry install

format-tests:
  stage: test
  script:
    - poetry run flake8 --count --select=E9,F63,F7,F82 --show-source --statistics --extend-exclude=docs/
    - poetry run flake8 --count --max-complexity=10 --max-line-length=79 --statistics
    - poetry run pylint carbonai --fail-under 9.5
    - poetry run mypy -p carbonai

pytest-tests:
  stage: test
  script:
    - poetry run coverage run -m --source=carbonai pytest tests
    - poetry run coverage report

build-private:
  stage: build
  script:
    - poetry build
  artifacts:
    paths:
      - dist
  only:
    - integration
  when: manual
  needs: ["pytest-tests"]

deploy-public:
  stage: deploy
  script:
    - poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD --build
  only:
    - master
  when: manual
  needs: ["pytest-tests"]

deploy-pages:
  stage: deploy
  script:
    - poetry run python docs/make.py html
    - mkdir public
    - cp -r docs/build/html/* public
  artifacts:
    paths:
      - public
  only:
    - master
  when: manual
