image: python:3.7-alpine

pages:
  stage: deploy
  script:
  - pip install -U sphinx sphinx-rtd-theme
  - sphinx-build -b html -a docs/source public
  - ls .
  - ls PyPowerGadget
  artifacts:
    paths:
    - public
  only:
  - master
