image: python:latest

stages:
  - .pre
  - test
  - build
  - deploy

dependencies:
  stage: .pre
  script:
    - pip install poetry
    - poetry install

tests:
  stage: test
  before_script:
    - poetry run flake8 --count --select=E9,F63,F7,F82 --show-source --statistics --extend-exclude=docs/
    - poetry run flake8 --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics
    - poetry run pylint CarbonAImpact
    - poetry run mypy -p CarbonAImpact
  script:
    - poetry run coverage run -m --source=CarbonAImpact pytest tests
    - poetry run coverage report
  needs: ["dependencies"]

build-private:
  stage: build
  script:
    - poetry build
  artifacts:
    paths:
      - dist
  only:
    - integration
  when: manual
  needs: ["tests"]

deploy-public:
  stage: deploy
  variables:
    PYPI_USERNAME: "capjohan"
    ***REMOVED***
  script:
    - poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD --build
  only:
    - master
  when: manual

deploy-pages:
  stage: deploy
  script:
    - poetry run python docs/make.py html
  artifacts:
    paths:
      - docs/build/html
  only:
    - master
  when: manual
