image: python:3.7-alpine

pages:
  stage: deploy
  script:
  - pip install -U sphinx sphinx-rtd-theme
  - mkdir public
  - cd docs
  - make html
  - cp -r build/html/* ../public
  artifacts:
    paths:
    - public
  only:
  - master
