image: python:latest

stages:
  - test
  - deploy

Dependencies:
  stage: before_script
  script:
    - pip install poetry
    - poetry install

Flake8:
  stage: before_script
  script:
    - poetry run flake8 --count --select=E9,F63,F7,F82 --show-source --statistics --extend-exclude=node_modules
    - poetry run flake8 --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics --extend-exclude=node_modules

Pylint:
  stage: before_script
  script:
    - poetry run pylint CarbonAImpact

Mypy:
  stage: before_script
  script:
    - poetry run mypy -p CarbonAImpact

Tests:
  stage: test
  script:
    - poetry run coverage run -m --source=CarbonAImpact pytest tests
    - poetry run coverage report

Deploy:
  stage: deploy
  script:
    - poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD --build
  only:
    - master
    - integration
# PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
# PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
# run: poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD --build
