name: Code quality and linting
on:
  push:
    branches:
      - main
      - fl_new_github_action
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ricardochaves/python-lint@v1.4.0
      with:
        python-root-list: "carbonai"
        use-pycodestyle: true
        use-flake8: true
        use-black: true
        use-mypy: true
        use-isort: true
        use-pylint: true
        extra-pylint-options: "--fail-under=8"
        # extra-pylint-options: ""
        extra-pycodestyle-options: ""
        extra-flake8-options: ""
        extra-black-options: ""
        extra-mypy-options: ""
        extra-isort-options: ""
