name: "Lint and evaluate quality of the code push on main branch"

on:
  push:         
    branches:
      - main

jobs:
  steps: 
    - name: Python Code Quality and Lint
    uses: ricardochaves/python-lint@v1.3.0
    with:
      python-root-list: "python_alelo tests"
      use-pylint: true
      use-pycodestyle: true
      use-flake8: true
      use-black: true
      use-mypy: true
      use-isort: true
      extra-pylint-options: ""
      extra-pycodestyle-options: ""
      extra-flake8-options: "--fail-under=9"
      extra-black-options: ""
      extra-mypy-options: ""
      extra-isort-options: ""