name: "Build and deploy Github pages"

on:
  push:         
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      - name: Install poetry
        run: pip3 install poetry

      - name: Install dependencies
        run: poetry install

      - name: Build docs
        run: poetry run python docs/make.py html

      - name: Deploy the doc
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/build/html # The folder the action should deploy.
